# Import PySide6 / PyQt6 modules
from agepy.interactive.util import import_qt_binding
qt_binding, QtWidgets, QtCore, QtGui = import_qt_binding()


class Ui_PhexDialog(object):
    def setupUi(self, PhexDialog):
        PhexDialog.setObjectName("PhexDialog")
        PhexDialog.resize(400, 224)
        font = QtGui.QFont()
        font.setPointSize(14)
        PhexDialog.setFont(font)
        self.grid_layout = QtWidgets.QGridLayout(PhexDialog)
        self.grid_layout.setObjectName("grid_layout")
        self.vp_group = QtWidgets.QGroupBox(parent=PhexDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vp_group.sizePolicy().hasHeightForWidth())
        self.vp_group.setSizePolicy(sizePolicy)
        self.vp_group.setObjectName("vp_group")
        self.vp_layout = QtWidgets.QHBoxLayout(self.vp_group)
        self.vp_layout.setObjectName("vp_layout")
        self.vp_input = QtWidgets.QSpinBox(parent=self.vp_group)
        self.vp_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vp_input.setObjectName("vp_input")
        self.vp_layout.addWidget(self.vp_input)
        self.grid_layout.addWidget(self.vp_group, 1, 0, 1, 1)
        self.el_group = QtWidgets.QGroupBox(parent=PhexDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.el_group.sizePolicy().hasHeightForWidth())
        self.el_group.setSizePolicy(sizePolicy)
        self.el_group.setObjectName("el_group")
        self.el_layout = QtWidgets.QHBoxLayout(self.el_group)
        self.el_layout.setObjectName("el_layout")
        self.el_input = QtWidgets.QComboBox(parent=self.el_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.el_input.sizePolicy().hasHeightForWidth())
        self.el_input.setSizePolicy(sizePolicy)
        self.el_input.setObjectName("el_input")
        self.el_layout.addWidget(self.el_input)
        self.grid_layout.addWidget(self.el_group, 0, 0, 1, 1)
        self.Jp_group = QtWidgets.QGroupBox(parent=PhexDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Jp_group.sizePolicy().hasHeightForWidth())
        self.Jp_group.setSizePolicy(sizePolicy)
        self.Jp_group.setObjectName("Jp_group")
        self.Jp_layout = QtWidgets.QHBoxLayout(self.Jp_group)
        self.Jp_layout.setObjectName("Jp_layout")
        self.Jp_input = QtWidgets.QSpinBox(parent=self.Jp_group)
        self.Jp_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Jp_input.setObjectName("Jp_input")
        self.Jp_layout.addWidget(self.Jp_input)
        self.grid_layout.addWidget(self.Jp_group, 1, 1, 1, 1)
        self.br_group = QtWidgets.QGroupBox(parent=PhexDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.br_group.sizePolicy().hasHeightForWidth())
        self.br_group.setSizePolicy(sizePolicy)
        self.br_group.setObjectName("br_group")
        self.br_layout = QtWidgets.QHBoxLayout(self.br_group)
        self.br_layout.setObjectName("br_layout")
        self.br_input = QtWidgets.QComboBox(parent=self.br_group)
        self.br_input.setObjectName("br_input")
        self.br_layout.addWidget(self.br_input)
        self.grid_layout.addWidget(self.br_group, 0, 1, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=PhexDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 2, 0, 1, 2)

        self.retranslateUi(PhexDialog)
        self.button_box.accepted.connect(PhexDialog.accept) # type: ignore
        self.button_box.rejected.connect(PhexDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PhexDialog)

    def retranslateUi(self, PhexDialog):
        _translate = QtCore.QCoreApplication.translate
        PhexDialog.setWindowTitle(_translate("PhexDialog", "Assignment Dialog"))
        self.vp_group.setTitle(_translate("PhexDialog", "v\'"))
        self.el_group.setTitle(_translate("PhexDialog", "El. State"))
        self.Jp_group.setTitle(_translate("PhexDialog", "J\'"))
        self.br_group.setTitle(_translate("PhexDialog", "Branch"))
