"""Load fluorescence spectra from scans."""

from __future__ import annotations

from dataclasses import dataclass
import os
import pickle
import numpy as np
import h5py

from agepy.spec.data import MetroValue
from agepy.spec.utils import load_metro_scan
from .spectrum import Spectrum

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from numpy.typing import NDArray
    from agepy.spec.anodes import PositionAnode
    from .qeff import QEff
    from .calib import Calib

    roi_tuple = tuple[tuple[float, float], tuple[float, float]]


@dataclass(frozen=True)
class ScanData:
    """Scan over a step variable with a fluorescence spectrum at
    each step and optional normalization data.

    Parameters
    ----------
    spectra: np.ndarray, shape (N,)
        Spectrum instances containing the fluorescence specrtra.
    steps: np.ndarray, shape (N,)
        Scan steps as float values.
    target_density: np.ndarray, shape (N,), optional
        Target density.
    photon_flux: np.ndarray, shape (N,), optional
        Beamline photon flux.

    """

    spectra: NDArray
    steps: NDArray
    target_density: NDArray | None = None
    photon_flux: NDArray | None = None
    bkg: Spectrum | None = None
    ref: Spectrum | None = None

    def save(self, filepath: str) -> None:
        """Save scan with pickle.

        Parameters
        ----------
        filepath: str
            Path to the file where the scan will be saved.

        """
        with open(filepath, "wb") as f:
            pickle.dump(self, f)


@dataclass
class Scan:
    data: ScanData
    anode: PositionAnode
    roi: roi_tuple = ((0, 1), (0, 1))
    qeff: QEff | None = None
    calib: Calib | None = None

    def counts(
        self,
        roi: bool = True,
        bkg: bool = True,
    ) -> tuple[NDArray, NDArray, NDArray]:
        """Get the photon counts for each step.

        Parameters
        ----------
        bkg: bool, optional
            Whether to subtract the background spectrum if available.

        Returns
        -------
        n: NDArray, shape (N,)
            The (normalized) counts.
        err: NDArray, shape (N,)
            The respective uncertainties.
        steps: NDArray, shape (N,)
            The corresponding step values.

        """
        # Parse the given calculation options
        roi = self.roi if roi else None
        bkg = self.bkg if bkg else None

        n = np.zeros_like(self.steps)
        err = np.zeros_like(self.steps)

        for i in range(len(n)):
            n[i], err[i] = self.data.spectra[i].counts(
                anode=self.anode, roi=roi, bkg=bkg
            )

        return n, err, self.steps

    def spectrum_at_index(
        self,
        idx: int,
        bkg: bool = True,
        qeff: bool = True,
        calib: bool = True,
    ) -> tuple[NDArray, NDArray]:
        """Get the fluorescence spectrum at a given index.

        Parameters
        ----------
        idx: int
            Step index.
        bkg: bool, optional
            Subtract the background spectrum if available.
        qeff: bool, optional
            Correct for quantum efficiencies if available.
        calib: bool, optional
            Apply the wavelength calibration if available.

        Returns
        -------
        spec: NDArray, shape (N,)
            The (normalized) counts.
        errs: NDArray, shape (N,)
            The respective uncertainties.

        """
        # Parse the given calculation options
        bkg = self.data.bkg if bkg else None
        qeff = self.qeff if qeff else None
        calib = self.calib if calib else None

        return self.data.spectra[idx].spectrum(
            anode=self.anode,
            roi=self.roi,
            bkg=bkg,
            qeff=qeff,
            calib=calib,
        )


def load_scan(
    file: str,
    raw: str = "dld_rd#raw",
    steps: str | None = None,
    target_density: str | None = None,
    photon_flux: str | None = None,
    scan_idx: str = "0",
    time: int = 1,
    skip_steps: list[int] | None = None,
    bkg: Spectrum | None = None,
    ref: Spectrum | None = None,
) -> ScanData:
    """Load a Scan from an h5 file generated by metro2hdf.

    Parameters
    ----------
    file: str
        Path to measurment hdf5 file processed by metro2hdf.
    raw: str, optional
        Path to the raw data in the h5 file.
    steps: str or None, optional
        Path to the measured step values. If `None` the step names
        are used.
    target_density: str or None, optional
        Path to the measured target density.
    photon_flux: str or None, optional
        Path to the measured photon flux.
    scan_idx: str, optional
        Scan index. In case of a single measurements / scan
        the index is usually `"0"`.
    time: int, optional
        Measurement time per step in seconds for normalization.

    Returns
    -------
    data: ScanData
        Dataclass containing the loaded data.

    """
    if not os.path.exists(file):
        errmsg = "Could not find h5 file"
        raise ValueError(errmsg)

    if not file.endswith((".h5", ".hdf5")):
        errmsg = "Unknown file type; expected hdf5"
        raise ValueError(errmsg)

    with h5py.File(file, "r") as h5:
        # Retrieve the raw events and step names (strings)
        step_vals, scan_raw = load_metro_scan(h5, raw, scan_idx)

        # Initialize spectra in a numpy array
        spectra = np.array([Spectrum(step_raw, time) for step_raw in scan_raw])

        # Convert step names to values or load measured values
        if steps is None:
            step_vals = np.array(step_vals, dtype=np.float64)

        else:
            scan = load_metro_scan(h5, steps, scan_idx)[1]
            # TODO: Account for mutiple values per step
            step_vals = np.array(scan, dtype=np.float64).flatten()

        # Retrieve target densities if specified
        if target_density is not None:
            scan = load_metro_scan(h5, target_density, scan_idx)[1]
            target_density = np.array([MetroValue(vals) for vals in scan])

        # Retrieve the photon flux if specified
        if photon_flux is not None:
            scan = load_metro_scan(h5, photon_flux, scan_idx)[1]
            photon_flux = np.array([MetroValue(vals) for vals in scan])

        # Remove steps at given indices
        if skip_steps is not None:
            mask = np.ones(step_vals.size, dtype=bool)
            mask[skip_steps] = False

            step_vals = step_vals[mask]
            spectra = spectra[mask]

            if target_density is not None:
                target_density = target_density[mask]

            if photon_flux is not None:
                photon_flux = photon_flux[mask]

    return ScanData(
        spectra,
        step_vals,
        target_density=target_density,
        photon_flux=photon_flux,
        bkg=bkg,
        ref=ref,
    )


def concat_scans(
    scans: list[ScanData],
    bkg: Spectrum | None = None,
    ref: Spectrum | None = None,
    sort_by_steps: bool = False,
) -> ScanData:
    """Load a Scan from an h5 file generated by metro2hdf.

    Parameters
    ----------
    scans: list
        Scan isntances to concatenate.

    Returns
    -------
    data: Scan
        Dataclass containing the concatenated scans.

    """
    spectra = []
    steps = []
    target_density = []
    photon_flux = []

    for scan in scans:
        spectra.append(scan.spectra)
        steps.append(scan.steps)

        if target_density is not None and scan.target_density is None:
            target_density = None

        else:
            target_density.append(scan.target_density)

        if photon_flux is not None and scan.photon_flux is None:
            photon_flux = None

        else:
            photon_flux.append(scan.photon_flux)

    # Concatenate the steps and spectra
    steps = np.concatenate(steps)
    spectra = np.concatenate(spectra)

    # Concatenate target densities
    if target_density is not None:
        target_density = np.concatenate(target_density)

    # Concatenate photon flux
    if photon_flux is not None:
        photon_flux = np.concatenate(photon_flux)

    # Sort if requested
    if sort_by_steps:
        sorted_inds = np.argsort(steps, kind="stable")

        steps = steps[sorted_inds]
        spectra = spectra[sorted_inds]

        if target_density is not None:
            target_density = target_density[sorted_inds]

        if photon_flux is not None:
            photon_flux = photon_flux[sorted_inds]

    return ScanData(
        spectra,
        steps,
        target_density=target_density,
        photon_flux=photon_flux,
        bkg=bkg,
        ref=ref,
    )
