"""Load fluorescence spectra from scans."""

from __future__ import annotations

from dataclasses import dataclass
import os
import pickle
import numpy as np
import h5py

from agepy.spec.data import MetroValue
from agepy.spec.utils import load_metro_scan
from .spectrum import Spectrum

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from numpy.typing import NDArray


@dataclass(frozen=True)
class Scan:
    """Scan over a step variable with a fluorescence spectrum at
    each step and optional normalization data.

    Parameters
    ----------
    spectra: np.ndarray, shape (N,)
        Spectrum instances containing the fluorescence specrtra.
    steps: np.ndarray, shape (N,)
        Scan steps as float values.
    target_density: np.ndarray, shape (N,), optional
        Target density.
    photon_flux: np.ndarray, shape (N,), optional
        Beamline photon flux.

    """

    spectra: NDArray
    steps: NDArray
    target_density: NDArray | None = None
    photon_flux: NDArray | None = None
    roi: tuple[tuple[float, float], tuple[float, float]] = ((0, 1), (0, 1))
    bkg: Spectrum | None = None
    ref: Spectrum | None = None

    def select_step_range(
        self,
        step_range: tuple[float, float] | None,
    ) -> tuple[NDArray, NDArray]:
        if step_range is None:
            return self.spectra, self.steps

        step_range = np.asarray(step_range, dtype=np.float64)

        if step_range.shape != (2,):
            errmsg = "step_range must be a tuple (min, max)."
            raise ValueError(errmsg)

        if step_range[1] < step_range[0]:
            errmsg = "step_range max < min."
            raise ValueError(errmsg)

        inds = np.argwhere(
            (self.steps >= step_range[0]) & (self.steps <= step_range[1])
        ).flatten()

        if len(inds) == 0:
            errmsg = f"No steps found in range {step_range}."
            raise RuntimeError(errmsg)

        return self.spectra[inds], self.steps[inds]

    def save(self, filepath: str) -> None:
        """
        Save a scan with pickle.

        Parameters
        ----------
        filepath: str
            Path to the file where the scan will be saved.

        """
        if not (filepath.endswith(".pkl") or filepath.endswith(".pickle")):
            errmsg = "filepath must end with '.pkl' or '.pickle'."
            raise ValueError(errmsg)

        with open(filepath, "wb") as f:
            pickle.dump(self, f)

    def counts(
        self,
        bkg: bool = True,
        step_range: tuple[float, float] | None = None,
    ) -> tuple[NDArray, NDArray, NDArray]:
        """Get the photon counts for each step.

        Parameters
        ----------
        bkg: bool, optional
            Whether to subtract the background spectrum if available.
        step_range: [float, float], optional
            Range of step values to consider. If None, all steps are
            used.

        Returns
        -------
        n: NDArray, shape (N,)
            The (normalized) counts.
        err: NDArray, shape (N,)
            The respective uncertainties.
        steps: NDArray, shape (N,)
            The corresponding step values.

        """
        # Parse the given calculation options
        bkg = self.bkg if bkg else None

        # Select the steps and corresponding spectra
        spectra, steps = self.select_step_range(step_range)

        n = np.zeros_like(steps)
        err = np.zeros_like(steps)

        for i in range(len(n)):
            n[i], err[i] = spectra[i].counts(roi=self.roi, bkg=bkg)

        return n, err, steps


def load_scan(
    file: str | list[str],  # TODO: list not implemented yet
    raw: str = "dld_rd#raw",
    steps: str | None = None,
    target_density: str | None = None,
    photon_flux: str | None = None,
    scan_idx: str = "0",
    time: int = 1,
) -> Scan:
    """Load a Scan from an h5 file generated by metro2hdf.

    Parameters
    ----------
    file: str
        Path to measurment hdf5 file processed by metro2hdf.
    raw: str, optional
        Path to the raw data in the h5 file.
    steps: str or None, optional
        Path to the measured step values. If `None` the step names
        are used.
    target_density: str or None, optional
        Path to the measured target density.
    photon_flux: str or None, optional
        Path to the measured photon flux.
    scan_idx: str, optional
        Scan index. In case of a single measurements / scan
        the index is usually `"0"`.
    time: int, optional
        Measurement time per step in seconds for normalization.

    Returns
    -------
    data: Scan
        Dataclass containing the loaded data.

    """
    if not os.path.exists(file):
        errmsg = "Could not find h5 file"
        raise ValueError(errmsg)

    if not file.endswith((".h5", ".hdf5")):
        errmsg = "Unknown file type; expected hdf5"
        raise ValueError(errmsg)

    with h5py.File(file, "r") as h5:
        step_vals, scan_raw = load_metro_scan(h5, raw, scan_idx)

        if steps is None:
            step_vals = np.array(step_vals, dtype=np.float64)

        else:
            scan = load_metro_scan(h5, steps, scan_idx)[1]
            # TODO: Account for mutiple values per step
            step_vals = np.array(scan, dtype=np.float64).flatten()

        if target_density is not None:
            scan = load_metro_scan(h5, target_density, scan_idx)[1]
            target_density = np.array([MetroValue(vals) for vals in scan])

        if photon_flux is not None:
            scan = load_metro_scan(h5, photon_flux, scan_idx)[1]
            photon_flux = np.array([MetroValue(vals) for vals in scan])

    spectra = np.array([Spectrum(step_raw, time) for step_raw in scan_raw])

    return Scan(
        spectra,
        step_vals,
        target_density=target_density,
        photon_flux=photon_flux,
    )
